version: '3.12'

services:
  coop_gardens_db:
    container_name: coop_gardens_db 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: coop_gardens
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coop_gardens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - coop-gardens-network
    command: ["postgres", "-c", "listen_addresses=*"] # Cho connect 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Email đăng nhập pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Mật khẩu đăng nhập pgAdmin
    ports:
      - "5050:80"  # Mở cổng 5050 trên máy host
    networks:
      - coop-gardens-network

volumes:
  pgdata:

networks:
  coop-gardens-network:
    driver: bridge


